### ISSUE TITLE
How to enable input other than English?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#1]
I am trying to construct an e-learning website using you project, however, being not able to submit contents using characters other than English letters. For example, 
1. Students can't use Chinese characters as their user names.
2. Can not input Chinese characters in calendar.

**Comment by inducer** [comment]
Generally, Relate has no problems with arbitrary Unicode characters. The two situations you mention are special, for the following reasons:

*   For my own application, I've designed Relate to use email-based sign-in for most of the users. In this case, there is no password, and students sign in by receiving a link in their email and clicking it. Their user name is thus equal to their email address, and email addresses put strict limits on what characters may appear where. I prefer this over letting the students set a password, because many of them would just use their university credentials, which in turn makes my Relate instance a more valuable hacking target. This can be changed though, and I'd be happy to make this configurable at some point. How urgently do you need this?

*   Event IDs (as well as page IDs) are currently forced consist of roman letters and underscores. Note that these IDs are completely independent of how these events are shown to the user however. In the file `events.yml`, you can customize user presentation:

    ```
    event_kinds:
        lecture:
            title: Lecture {nr}
            color: blue

        exam:
            title: Exam {nr}
            color: red
    ```

    http://documen.tician.de/relate/content.html#calendar-and-events

    If it helps your use case, more general characters could be allowed.

**Comment by dzhuang** [comment]
Thank you for your reply and your patience!  I am going to open the course in about a week. And I will be appreciated if you can make username based sign-in available.

**Comment by hsingh23** [comment]
As a user of the system - having to log in once from a browser is very easy and I prefer it to username based sign-in. Could you please explain why you require username password login?

**Comment by inducer** [comment]
User/pw auth is now available.

Use
```
STUDENT_SIGN_IN_VIEW = "course.auth.sign_in_by_email"
```
to enable it.

**Comment by dzhuang** [comment]
inducer, thank you very much.
