### ISSUE TITLE
viewing multiplechoicequestion in Analytics Overview gives 500 server error

### ISSUE THREAD

**Issue by lukeolson** [inducer/relate#105]
In the Analytics Overview, viewing choicequestions gives the statistics just fine.  Viewing a multiplechoicequestion yields 500 server error.

The traceback:

```
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "./course/utils.py", line 479, in wrapper
   response = f(pctx, *args, **kwargs)
 File "./course/analytics.py", line 508, in page_analytics
   grading_page_context, visit.page_data.data, visit.answer)
 File "./course/page/choice.py", line 390, in normalized_answer
   [permutation[idx] for idx in choice],
TypeError: 'int' object is not iterable
```

**Comment by inducer** [comment]
@dzhuang, can you take a look?

**Comment by dzhuang** [comment]
I tested the sample successfully. @lukeolson can you post your MultipleChoiceQuestion here?

**Comment by inducer** [comment]
Have to agree with @dzhuang, the code looks fine. Did you have this question as a single-select choice question at one point? If you have, that's why you're seeing this. I've added a warning in e0d14e7.

#107 would address this.

To clean up the mess, you likely need to go find the flow page visits that have the wrong type 'answer' and delete them.

Closing for now.

**Comment by dzhuang** [comment]
Thank you!

**Comment by lukeolson** [comment]
This is exactly what happened.  I changed the question type, but not the id.
