### ISSUE TITLE
How to determine the offset (date or week) of a course?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#11]
If I am not wrong, using `if_before: end_week N` is easy to run a course by `adding further modifiers` without manual adjust the date/time rule in `ISO-formatted dates/time` format. So, if the offset (starting date/time) of the course is set, then other time is determined. However, I can't find in documentations about the setting the offset variable in `course.yaml`.

**Comment by inducer** [comment]
"Events" are what makes this possible:
http://documen.tician.de/relate/content.html#calendar-and-events

They're stored in the database (rather than the YML course material), and so they can change from one edition of the course to the next while leaving the course material the same.

If you want what you suggest (which is to have everything offset from the start date of the course), you would create one event, say `start_of_course`, and then express all dates as, say `start_of_course + 3 weeks` or `start_of_course + 3 weeks + 1 day @14:50`. But you're also free to have as many events as you like, and fix those to more natural anchor points (that may shift from one run of the class to the next), such as `lecture_on_foo`. To give you an idea, I mainly use events for `homework_due` and `lecture 12` as anchor points.
