### ISSUE TITLE
Imported grades not updated in grading page

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#190]
I graded a flow with excel and the grades are imported as csv. However, in the grading/flow-page, "Points awarded" of those flow still marked as "(unknown)“ while it display correctly in the gradebook.

**Comment by inducer** [comment]
The gradebook and the flow grading system are distinct, and there's a one-way flow of information "flows->gradebook". In particular, the flows have an idea of their results, but if you override flow grades from the gradebook, they won't show up as the flow result. Worse, if you click regrade, your manually entered grades will be overwritten in the gradebook.

So I'd recommend doing the following in your situation:

* Hide the flow result, to avoid confusion: https://documen.tician.de/relate/flow.html#course.constants.flow_permission.cannot_see_flow_result

* Create a *separate* grading opportunity for the grades from that flow, and use that to import your grades from Excel.

As a separate question, how come you felt the need to do grading in Excel rather than the built-in grading interface?

**Comment by dzhuang** [comment]
Thanks. I will try to understand the mechanism.

For your separate question, I am using import because in a specific flow, I asked students to submit a protected xls file. When the flow due, I bulk downloaded those files and used VBA to grade their answers, and the grade data were automatically written into an Excel file. That automation process can't be done in linux environment on my server.

**Comment by inducer** [comment]
OIC, makes sense. Thanks for answering--I was just curious.

**Comment by inducer** [comment]
I'll close this issue. Feel free to reopen if there's something related to this that needs to be done.
