### ISSUE TITLE
Extending email setting

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#195]
I think there might be necessity to extend the settings of email configuration both at project level and course level. My initial idea is:

 1. at project level, add the following in local_settings.py:
      1. whether the email service used allow sending emails with different domain name, as discussed in #41 
      1. optionally a no-reply email addr for register/reset passwd. If none, use robot email.

 1. at course level
      1. whether TAs will receive email, and which kinds of email they will receive.
      1. reply-to settings of different events, who will receive response from participants regarding enroll decision/grading feedback/etc.

**Comment by inducer** [comment]
Sure, that sounds good. I'd be happy to see an implementation of that.

**Comment by dzhuang** [comment]
I think I need some advice.

1. May I parse the ``from_email`` and ``notify_email`` from course.yml rather than by saving a ``course.models.course`` instance from ``course.versioning.CourseCreationForm``? So that I don't need to manually input those values and I can select from a queryset which include the emails of tutor and TA in admin. 

1. I think at flow/page level, email might also need some configurations. 
    1. Sometimes the tutor is responsible for reviewing/grading/responding to some difficult flows (with human graded questions), TAs are responsible for other simpler flows. To achieve that, I think of adding a ``allowed_attribute`` named ``flow_reviewer``, which is default to ``course_reviewer`` if not defined, where course_reviewer can be set to TA or tutor.  
    1. For a single flow, there can also be difficult questions which require the review of tutor, and simple ones which require TAs to do the review. To achieve that, we can add a ``allowed_attribute`` named ``page_reviewer``, which is default to ``flow_reviewer`` if not defined.
    1. If the above settings are ok, response of grading feedback from participants will be sent to those reviews, and we can also extend some functionality like informing TA's to review flows and pages by automatic emails.

Can you provide some more advices, or pros and cons of my idea?

**Comment by inducer** [comment]
1) I moved those from .yml content to the database on purpose, so I'd rather not see them go back, since they're more "daily operations" than "course content", and so I feel like they belong where they are. We could have them autocomplete from the user list though--as long as we allow custom entries, too.

2.i) I'm thinking of redoing the course permission/role system at some point, where the set "instructor"/"ta"/... becomes data rather than hard-coded concept, with a number of permissions attached. We could then add a "grading" section to the rules. This would provide an answer for #170 along with solving your use case, I thnk.

2.ii) There's already a notion of per-page rules--this would just need to be extended to the grading rules.

2.iii) I'm not in principle against this, although there's a potential for this to generate *tons* of email. (I teach classes with ~200 people in them.) But I feel we should firm up the design for the first two before embarking on this one.

**Comment by dzhuang** [comment]
Thanks for your reply, then I'd better just consider the email settings at project level, and wait for your improvements on flow/page permissions and rules.

For the email notifications, I think I'd rather notify reviewers when flows are due according to rules, and give a daily summary email when there are late submission. That may not be disastrous.

**Comment by dzhuang** [comment]
Fixed by e98631b8bc1eb6225d98a4761036c747cb9e292f.
