### ISSUE TITLE
Cannot_see_flow_result permission not applying to gradebook

### ISSUE THREAD

**Issue by eecarrier** [inducer/relate#216]
The cannot_see_flow_result permission should make it so that the score doesn't appear in the student gradebook.  It'd be fine for the line to still appear in the student gradebook, just instead of score have the "no result shown".  This would eliminate the need to remember to hide/unhide the whole entry in the student gradebook and seems like it would be less confusing to the students.

**Comment by inducer** [comment]
That's actually tricky/expensive to do, since Relate would have to evaluate flow permissions for each grade it shows. It's easy to add a "show/hide  results" knob in addition to the "show/hide row". It's also easy to make  the "edit grading opportunity" form more easily accessible from the gradebook. Would that help?

**Comment by eecarrier** [comment]
Both of those would help, but it's not that big of a deal/easiest enough to manage if you don't have the time.  Just thought it was worth mentioning in case it was easy.

**Comment by inducer** [comment]
The code to do this is now there. It'll go live at UIUC with a bigger batch of changes sometime soon.

**Comment by inducer** [comment]
Now live.
