### ISSUE TITLE
"Optional" questions shouldn't produce unanswered question warnings

### ISSUE THREAD

**Issue by earwig** [inducer/relate#219]
The warning when trying to submit about unanswered questions is useful, but some questions are optional and often won't have an answer (I'm thinking of instructor-feedback things). Leaving these blank shouldn't require confirmation and use the warning styling (though it might be good to mention nonetheless).

**Comment by inducer** [comment]
That's a good point. Thanks for the report.

Now that #217 is  in, I'd call this less urgent, since you can see what question it's talking about. But it should still not complain at all.

**Comment by dzhuang** [comment]
Happen to see this issue. I think the point is good, as I am creating some pre-quiz sessions which are not supposed to generate grades, and of course all those page should be "Optional". 

Sometimes we want to include a question/questions using relate built-in questions, however, an optional question should not have a point value, I think maybe we need to add an ``allowed_attr`` such as ``optional`` to all the question types, which require something to be done on existing ``required_attr``, for example, iff ``optional`` presents, then ``value`` and ``rubric`` should become and ``allowed_attr`` so that student won't get confused and also for the page to pass the validation.

**Comment by inducer** [comment]
I'd be OK with that suggestion. Could you send a patch?

**Comment by dzhuang** [comment]
I am now preparing for the patch. Inspired by your comments in #269 , I think maybe we can do this better:  set ``value`` point as an ``allowed_attr`` rather than a ``required_attr``, and add another ``allowed_attr`` named ``optional``. When neither ``value`` nor ``optional`` is used in page_desc, it raises validation error.

**Comment by inducer** [comment]
What would happen for
```
value: 15
optional: True
```
? Would this be "extra credit", i.e. not be counted towards the max points?

**Comment by dzhuang** [comment]
Sorry for didn't notice your comments. I think it should not be counted towards the max points, because that will make ``optional``  irrelevant. We can generate some warning in validation that the value attribute is bypassed when both ``value`` and ``optional`` presented.

**Comment by inducer** [comment]
OK, that sounds reasonable.

**Comment by inducer** [comment]
Closed as of 066cc2af75bf75f3742a67a148c0c148ef55a96c.
