### ISSUE TITLE
Issue about time rule

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#23]
When I set the "if_before" rule for a flow using absolute time(iso format, e.g. "2015-5-10 14:13"), the rule never functioned and students were able to start new session after the due time. However, If I set fake time, the rule works. Another thing I noticed is the time displayed when I tried to regrade or recompute the grade, for example:

```
Session grade recomputed at 2015-05-05 15:29:09.570974+08:00.
Session regraded at 2015-05-05 15:29:31.564501+08:00.
```

I think the substring `+08:00` is the result of  the `TIME_ZONE = 'Hongkong'` setting in `local_settings.py`. However, are there something wrong which make time not comparable so that the expiration rule will not be activated? are there any connection with the weird format of time string?

**Comment by dzhuang** [comment]
I see there's a `parse_date_spec` function with `return_now_on_error` default `True`. Seems the reason is `parse_date_spec` failed to parse the time and return `now()` as the results.

**Comment by inducer** [comment]
Right. The reason for this whole mess is that when you first create a course that relies on a bunch of events, all of these events are not known, because the course needs to exist first in order for you to create the events. On the other hand, the course content doesn't make sense without the events in place. That's a circular dependency, and it needs to be broken somehow.

The way I chose to do that was by parsing unknown events as "right now" (the flag you found) and letting the user check which date/time fields encountered an error while parsing. (Content > Check Events) If you've got a better suggestion, I'd be happy to hear it.

But even with the existing feature, I think the UI could stand to be renamed and reshuffled a bit. (Possibly: Check date validity?) I'll work on that.

**Comment by inducer** [comment]
47a5b91 should significantly improve the usability of this. Unrecognized date/time specifications now generate warnings during update, which is more natural (and more visible) than the hidden "check events" feature.

**Comment by dzhuang** [comment]
Validation failed for course content for flows using time with the ISO format since your latest commit. Maybe I should dive into the logic and relationships between events and time setting. Thank you.

**Comment by inducer** [comment]
Should be fixed in 2e1426e, tested in sample content:

https://github.com/inducer/relate-sample/commit/03f9f6c6645c537d4d4634c8d53b54551a3eff37

**Comment by dzhuang** [comment]
Now I can be confident to say I understand the relationship between events and time rule, I think it's really a good idea! Thank you. Now the problem is, under what circumstance will the ISO format time function?

**Comment by inducer** [comment]
It'll be viewed as an ISO timestamp if YAML parses it as one.

See example 2.22 here:
http://www.yaml.org/spec/1.2/spec.html#id2761292
