### ISSUE TITLE
Inline questions failed to show form validation error messages.

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#266]
The bug seems to be caused by [here](https://github.com/inducer/relate/blob/8d79aa1ca02beacaf4ec545ce6125efa5011e78a/course/templates/course/custom-crispy-inline-form.html#L48). I'll submit a PR to solve this.

**Comment by inducer** [comment]
Sounds good. Could you submit the MR here instead: https://gitlab.tiker.net/inducer/relate

I just created an account for you. That has the positive side effect that the tests will run automatically.

Thanks!

**Comment by dzhuang** [comment]
Ok.

**Comment by dzhuang** [comment]
It seems I need to sign in into the project. Please email the username to dzhuang.scut@gmail.com, thanks.

**Comment by inducer** [comment]
I did. Can you check your spam folder? These emails have a habit of going there. Sorry!

**Comment by inducer** [comment]
Also the site will be offline for a little because of [this](https://about.gitlab.com/2016/12/05/cve-2016-9469/?mkt_tok=eyJpIjoiWWpnMVptRXlaR1UxWVRWbSIsInQiOiJBc2hkV0R4MkQ3Q1FPRHdKRExQUXpKckpNcVEzQitpd2pBMk5aV241Y1dRVzNnbUNyMDFRRnBlZXgwUENnSDZ4KzVhSXlqQkFvb3gyQk1vNHRjcEpQQ1Q4UFwvYzU3NW5WSmJnMXRkcVNCXC84PSJ9). Should be back shortly.

**Comment by inducer** [comment]
It's back.

**Comment by dzhuang** [comment]
Thanks. I found it in the spam and I'm now in.
