### ISSUE TITLE
If a flow session has no answer, then the grade_aggregation_strategy will fail.

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#34]
I have a flow with a use_latest strategy. A student opened 3 sessions, with first 2 have None answer, and provide answer in the last session. Then it failed to provide the final points.

**Comment by inducer** [comment]
FWIW, the code that implements this is here:

* https://github.com/inducer/relate/blob/master/course/models.py#L1104
* https://github.com/inducer/relate/blob/master/course/models.py#L1182

I could see one thing wrong with it, namely that the obtained `valid_percentages` are never sorted by anything, so *if* multiple grade outcomes exist, it was not determined which one should be used. That's fixed in 0b1129b (by sorting by the grade time), but I doubt that was your issue, since the code I linked (even in its original form) *should* only consider grades that aren't None. So I don't understand why the final computed grade is None. I was also unable to reproduce this in my testing. Could you sprinkle some print statements into the code and figure out what's wrong?

**Comment by dzhuang** [comment]
Thank you and sorry for late response. I will try to find out what's wrong with it.

**Comment by dzhuang** [comment]
Currently I cannot reproduce the error, don't know whether its my fault. Close it right now.
