### ISSUE TITLE
Starting a new course with the default repo fails

### ISSUE THREAD

**Issue by davis68** [inducer/relate#501]
Currently starting a new course with the default repo fails with the message:

    Course creation failed: ValidationError: flows/001-linalg-recap.yml, group 1 ('main'), page 3 ('ipynb'): attribute content: UndefinedError: 'render_notebook_cells' is undefined

**Comment by inducer** [comment]
Thanks for reporting this. This is a UIUC operations concern more than an upstream concern. Course creation with that repo gets tested with every commit on master, so that does work--but the UIUC instance has fallen behind by a fair bit. It'll get upgraded during break, likely Monday. A few things that have been broken (table search, progress tracking) should also start working again then.

**Comment by inducer** [comment]
(Closing here.)

**Comment by inducer** [comment]
FWIW, this should be fixed as of Monday night.
