### ISSUE TITLE
Batch impose deadline fails

### ISSUE THREAD

**Issue by eecarrier** [inducer/relate#517]
When batch imposing deadlines with past due only selected, it fails entirely to expire sessions.  The failure message given is shown in the picture below.
[Screen Shot 2018-03-28 at 4.28.09 PM.pdf](https://github.com/inducer/relate/files/1858022/Screen.Shot.2018-03-28.at.4.28.09.PM.pdf)

**Comment by inducer** [comment]
![bildschirmfoto von 2018-03-28 17-52-47](https://user-images.githubusercontent.com/352067/38060559-da8c4d60-32b0-11e8-93da-43c54f3b4d0f.png)

**Comment by inducer** [comment]
I believe this is due to the having switched from pickle serialization to JSON serialization for task calls.

See http://docs.celeryproject.org/en/latest/userguide/calling.html#serializers.

#518 should address this.

As a UIUC ops matter, I will apply that fix tonight after the CBTF closes. (11pm I believe) Hope that's soon enough.

**Comment by inducer** [comment]
Fix applied.  @eecarrier It'd be great if you could let me know if this helped.

**Comment by eecarrier** [comment]
Just tested and that fixed the issue. Thanks for getting it applied so quickly!
