### ISSUE TITLE
login gets blocked by djange CSRF

### ISSUE THREAD

**Issue by KlavsKlavsen** [inducer/relate#901]
and Log says: 
```
Forbidden (Origin checking failed - https://relate.example.com does not match any trusted origins.): /login/user-password/ 
```
I cannot find any setting for this in local_settings.py ?
I have 3 hosts in my ALLOWED_HOSTS: relate (used by kubernetes health check), relate.sub.example.com and relate.example.com - and RELATE_BASE_URL is set to https://relate.example.com
Any ideas whats up?

p.s. once I've got the final details ironed out, I'll submit a k8s Helm chart + Dockerfile PR - supporting rollout of relate in k8s - if interested? I've based it on https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets - and removed "irrelevant stuff" - and added a few improvements to support setting a few relevant config variables for relate - but basing it off that - still makes it apache 2.0 licensed for the "original part" :)

**Comment by KlavsKlavsen** [comment]
found this https://stackoverflow.com/questions/38841109/csrf-validation-does-not-work-on-django-using-https - seems I need to figure out where to set CSRF_TRUSTED_ORIGINS

**Comment by KlavsKlavsen** [comment]
But no such setting exists in relate codebase ?

**Comment by inducer** [comment]
Any Django settings can be also be set in `local_settings.py`. I'm still not sure why you're seeing the origin checking message. What's the URL of the page that's posting the login form?

>p.s. once I've got the final details ironed out, I'll submit a k8s Helm chart + Dockerfile PR - supporting rollout of relate in k8s - if interested

Yes, I'd be interested in that, particularly if it's something that can be exercised by CI, so that I don't accidentally break it. TBH, I haven't yet bothered to learn how to get off of my 1970s approach to infrastructure, so this might be an opportunity.

**Comment by KlavsKlavsen** [comment]
Setting that in local_settings.py resolved it..  On to getting my first quiz working - and then I'll clean this up for submitting next week. Thank you for your assistance :)
